# Generated by Django 2.2.2 on 2019-07-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsongs',
            field=models.ManyToManyField(related_name='newsongs', to='recommend.Song'),
        ),
    ]
