# Generated by Django 2.2.2 on 2019-07-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_customuseradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='songs',
            field=models.ManyToManyField(to='recommend.Song'),
        ),
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
