# Generated by Django 2.2.2 on 2019-08-12 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommend.Song'),
        ),
    ]
