# Generated by Django 2.2.2 on 2019-08-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('recommend', '0004_auto_20190812_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
