# Generated by Django 2.2.2 on 2019-07-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_customuseradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommends',
            field=models.ManyToManyField(related_name='custom_user_recommends', to='recommend.Song'),
        ),
        migrations.DeleteModel(
            name='CustomUserAdmin',
        ),
    ]
